[project]
name = "order-support-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lbest16", email = "bfglz@yahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]<2",
]

[project.scripts]
order-support-assistant = "order_support_assistant:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
